"""
Scam Shield - Cybercrime Report Helper
Generates structured complaint drafts formatted for the National Cyber Crime Reporting Portal
(cybercrime.gov.in / 1930 Helpline / Sanchar Saathi Chakshu).
"""

from __future__ import annotations
from datetime import datetime, timezone
try:
    from .models import ReportDraft, ExtractedEntities, ScamCategoryType
except (ImportError, ValueError):
    from models import ReportDraft, ExtractedEntities, ScamCategoryType


CATEGORY_TITLES: Dict[str, str] = {
    "KYC_BANK": "Online Banking / KYC Update Phishing Fraud",
    "PARCEL_COURIER": "Fake Courier / Customs Seizure Extortion Fraud",
    "JOB_TASK": "Work-From-Home / Telegram Prepaid Task Investment Fraud",
    "LOAN_APP": "Illegal / Predatory Instant Loan App Harassment Fraud",
    "DIGITAL_ARREST": "Impersonation of Police/CBI / Fake Digital Arrest Extortion",
    "UTILITY_BILL": "Electricity / Utility Bill Disconnection Phishing Fraud",
    "LOTTERY_PRIZE": "Lottery / Prize / KBC Winner Impersonation Fraud",
    "UPI_COLLECT": "UPI Collect Request / Fake QR Code Refund Fraud",
    "INVESTMENT_CRYPTO": "Fraudulent Stock / Crypto Trading Scheme",
    "ROMANCE": "Dating / Matrimonial Romance Extortion Fraud",
    "PHISHING_LINK": "Malicious Phishing URL / Credential Theft Incident",
    "OTHER": "Suspicious Cyber Incident / Unsolicited Fraud Communication",
    "NONE": "Inquiry / Unverified Communication"
}


def build_report_draft(
    message_text: str,
    scam_category: ScamCategoryType,
    sender: Optional[str],
    entities: ExtractedEntities,
    red_flags: List[str]
) -> ReportDraft:
    """
    Constructs a pre-filled formal cybercrime report draft for Indian cybercrime authorities.
    Does NOT auto-submit; provides user with ready-to-copy evidence text.
    """
    now_str = datetime.now(timezone.utc).strftime("%d-%m-%Y %H:%M UTC")
    category_title = CATEGORY_TITLES.get(scam_category, "Online Cyber Fraud Incident")

    # Suspect identifiers
    suspect_parts = []
    if sender:
        suspect_parts.append(f"Sender / Caller ID: {sender}")
    if entities.phones:
        suspect_parts.append(f"Associated Phone Number(s): {', '.join(entities.phones)}")
    if entities.upi_ids:
        suspect_parts.append(f"Associated UPI ID(s): {', '.join(entities.upi_ids)}")
    if entities.urls:
        suspect_parts.append(f"Fraudulent Link(s) / Domains: {', '.join(entities.urls)}")

    suspect_text = "\n".join(suspect_parts) if suspect_parts else "No specific sender/link provided."

    # Loss amount if detected
    loss_amount = ", ".join(entities.amounts) if entities.amounts else "Not specified / Attempted fraud"

    # Red flag summary
    flags_formatted = "\n".join(f"- {flag}" for flag in red_flags) if red_flags else "- Suspicious unsolicited fraud pattern"

    full_complaint = f"""COMPLAINT DRAFT FOR NATIONAL CYBER CRIME REPORTING PORTAL (cybercrime.gov.in)
--------------------------------------------------------------------------------
INCIDENT DATE & TIME: {now_str}
CATEGORY OF COMPLAINT: {category_title}
SUSPECTED ACCUSED DETAILS:
{suspect_text}

DEMANDED / ATTEMPTED AMOUNT: {loss_amount}

INCIDENT SUMMARY & RED FLAGS:
The complainant received unsolicited fraudulent communication aiming to mislead and defraud.
The following malicious tactics and red flags were verified:
{flags_formatted}

ORIGINAL FRAUDULENT MESSAGE RECEIVED:
\"\"\"
{message_text.strip()}
\"\"\"

PRAYER / ACTION REQUESTED:
1. Block the offending mobile numbers/SIM cards via DoT Sanchar Saathi / Chakshu.
2. Freeze the recipient UPI VPAs/Bank accounts associated with this syndicate.
3. Block the fraudulent phishing domains/IPs to protect other citizens.
--------------------------------------------------------------------------------
Generated by Scam Shield (Solo Cyber Safety Hackathon Project).
Dial 1930 immediately if any monetary transaction has occurred.
"""

    return ReportDraft(
        incident_date=now_str,
        category=category_title,
        incident_summary=f"Incident of {category_title} reported on {now_str}.",
        suspect_identifiers=suspect_text,
        evidence_text=message_text.strip(),
        reported_loss_amount=loss_amount,
        helpline_number="1930",
        portal_url="https://cybercrime.gov.in",
        chakshu_url="https://sancharsaathi.gov.in/sfc/",
        full_complaint_text=full_complaint.strip()
    )
